call plug#begin('~/.vim/bundle')

" Plugins
if (has("python") || has("python3")) && has("timers") && has("lambda")
    Plug 'maralla/completor.vim'
endif
Plug 'itchyny/lightline.vim'
Plug 'tmhedberg/SimpylFold', {'for':'python'}
Plug 'vim-scripts/indentpython.vim', {'for':'python'}
Plug 'tpope/vim-fugitive'
Plug 'Yggdroot/indentLine'
Plug 'vimwiki/vimwiki'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'fatih/vim-go', {'do': ':GoUpdateBinaries'}
Plug 'SirVer/ultisnips'
Plug 'w0rp/ale'

" Color schemes
Plug 'dikiaap/minimalist'

" Local plugins
if filereadable(expand("~/.config/nvim/vimplug.local"))
    source ~/.config/nvim/vimplug.local
endif

" End vim-plug stuff
call plug#end()

" Leader
let mapleader = ","
nmap <Leader>s :set spell!<CR>

"set termguicolors 
colorscheme minimalist
autocmd ColorScheme * hi Comment ctermfg=darkgray ctermbg=NONE cterm=NONE guifg=#444444 guibg=NONE gui=NONE

" Misc stuff
filetype plugin indent on
syntax on
set tabstop=4 shiftwidth=4 expandtab
set nu
set relativenumber
set formatoptions-=cro
set hidden
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1
set wrap
set linebreak
set nohlsearch
set ignorecase
set smartcase
set conceallevel=0

" Window navigation
nnoremap <C-l> <C-w><C-l>
nnoremap <C-h> <C-w><C-h>
nnoremap <C-k> <C-w><C-k>
nnoremap <C-j> <C-w><C-j>
nnoremap <C-c> <C-w>c

" Add code folding and remap to space
set foldmethod=syntax
set foldlevel=99
nnoremap <leader>f za

" Indentline configuration
let g:indentLine_color_term = 239
let g:indentLine_char = '┆'
let g:indentLine_enabled = 1

" Settings for completer
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>\<cr>" : "\<cr>"

" Settings for ALE
let g:ale_completion_enabled = 0
let g:ale_lint_on_text_changed = 'never'

" Settings for fzf
nnoremap <leader>e :Files<CR>
nnoremap <leader>b :Buffers<CR>
nnoremap <leader>/ :BLines<CR>

" vimwiki
let g:vimwiki_list = [{'path': '~/.local/vimwiki/'}]

" Settings for lightline
let g:lightline = {
            \   'colorscheme': 'wombat',
            \   'active': {
            \       'left': [ [ 'fugitive', 'paste' ], [ 'readonly', 'filename', 'modified'] ]
            \   },
            \   'component': {
            \       'fugitive': '%{exists("*fugitive#head")?fugitive#head():""}',
            \   },
            \   'component_visible_condition': {
            \       'fugitive': '(exists("*fugitive#head") && ""!=fugitive#head())'
            \   }
            \ }

" Settings for UltiSnips
let g:UltiSnipsSnippetDirectories = ['~/.config/nvim/UltiSnips', 'UltiSnips']
let g:UltiSnipsExpandTrigger="<c-space>"

" Go settings
augroup filetype_go
    let g:go_fmt_command = "goimports"
    autocmd FileType go nmap <C-]> :GoDef<CR>
    autocmd FileType go nmap <leader>d :GoDoc<CR>
    autocmd FileType go nmap <leader>m :GoBuild<CR>
augroup END

" Python settings
augroup filetype_python
    autocmd!
    autocmd FileType python let python_highlight_all=1
augroup END

" LaTeX settings
augroup filetype_text
    autocmd!
    let g:tex_conceal="a"
    autocmd FileType tex set breakindent
    autocmd BufWritePost *.tex call jobstart('pdflatex '.expand('%').' && killall -HUP mupdf')
    autocmd FileType tex command LP call jobstart('mupdf '.expand('%:r').'.pdf')
    autocmd FileType tex set synmaxcol=80
    autocmd FileType tex nnoremap j gj
    autocmd FileType tex nnoremap k gk
augroup END

" C++ settings
function AlternateFile()
    let ext = expand('%:e')
    if ext == 'h'
        e %<.cpp
    else
        e %<.h
    endif
endfunction

augroup filetype_cpp
    autocmd!
    autocmd FileType cpp let b:ale_linters = ['gcc']
    autocmd Filetype cpp nmap <Leader>m :make<CR>
    autocmd Filetype cpp nmap <Leader>s :silent call AlternateFile()<CR>
augroup END

" Completor settings
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<cr>"

" Load in local vimrc
if filereadable(expand("~/.vimrc.local"))
    source ~/.vimrc.local
endif
