#! /usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/../local.conf

service_name=$OPENVPN_SERVICE
if [ -z $OPENVPN_SERVICE ]; then
    exit 0
fi

running_str="$(ip r | grep -E '0\.0\.0\.0/1 via [0-9\.]+ dev tun0')"

if [ -z $running_str ]; then
    echo "  vpn off"
else
    ready_str="$(systemctl status $service_name | grep 'Initialization Sequence Completed')"
    if [ -z "$ready_str" ]; then
        echo "  initializing..."
    else
        #echo "  vpn on"
        echo "  vpn on"
    fi
fi
