#! /usr/bin/env bash

service_name="openvpn-client@mullvad-gb.service"
running_str="$(ip r | grep -E '0\.0\.0\.0/1 via [0-9\.]+ dev tun0')"

if [ -z $running_str ]; then
    echo "  vpn off"
else
    ready_str="$(systemctl status $service_name | grep 'Initialization Sequence Completed')"
    if [ -z "$ready_str" ]; then
        echo "  initializing..."
    else
        echo "  vpn on"
    fi
fi
