#! /bin/bash

OPTS=("full screen" "selection")
case "$( printf '%s\n' "${OPTS[@]}" | rofi -dmenu )" in
    "full screen")
        scrot -e 'xclip -selection clipboard -t image/png $f; mv $f ~/Documents/screenshots/'
        ;;
    "selection")
        scrot -s -e 'xclip -selection clipboard -t image/png $f; mv $f ~/Documents/screenshots/'
        ;;
esac
