# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _correct
zstyle ':completion:*' insert-unambiguous false
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=** r:|=**'
zstyle ':completion:*' max-errors 2
zstyle ':completion:*' menu select=long
zstyle ':completion:*' original true
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle :compinstall filename '/home/daniel/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt HIST_IGNORE_SPACE
setopt extendedglob
unsetopt beep notify
# End of lines configured by zsh-newuser-install

# Load up editor when hitting ^x^x
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^x^x' edit-command-line

# Vim keybindings
bindkey -v

# modify the path
export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:/sbin"
export PATH="$PATH::/opt"

# go path
if [ -d "$HOME/src" ]; then
    export GOPATH="$HOME/src/go"
else
    export GOPATH="$HOME/Sources/go"
fi
export PATH="$PATH:$GOPATH/bin"
if [ ! -d $GOPATH ]; then
    mkdir -p $GOPATH
fi

# npm path
export PATH="$PATH:$HOME/.local/npm-global/bin"

# misc
alias e='nvim'
alias ef='nvim -c :Files'
alias vim='nvim'
alias t='tmux'

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Local
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

# Starship for prompt
command -v starship &>/dev/null && eval "$(starship init zsh)" || echo "starship not found in PATH — install it: https://starship.rs"

# Plugins
ZSH_PLUGIN_DIR="$HOME/.config/zsh/plugins"

ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=30
ZSH_AUTOSUGGEST_USE_ASYNC=1
ZSH_AUTOSUGGEST_MANUAL_REBIND=1
ZSH_AUTOSUGGEST_HISTORY_IGNORE="cd *"
[ -f $ZSH_PLUGIN_DIR/zsh-autosuggestions/zsh-autosuggestions.zsh ] && source $ZSH_PLUGIN_DIR/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey '^ ' autosuggest-accept
