# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _correct
zstyle ':completion:*' insert-unambiguous false
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=** r:|=**'
zstyle ':completion:*' max-errors 2
zstyle ':completion:*' menu select=long
zstyle ':completion:*' original true
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle :compinstall filename '/home/daniel/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt extendedglob
unsetopt beep notify
# End of lines configured by zsh-newuser-install

autoload -U colors
colors

# VCS info in prompt
setopt PROMPT_SUBST
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' stagedstr "%F{green}●%f"
zstyle ':vcs_info:*' unstagedstr "%F{red}●%f"
zstyle ':vcs_info:git*' formats "%{$fg[green]%}%c%u%{$fg[green]%}%b%{$reset_color%}"
precmd() {
    vcs_info
    RPROMPT="${vcs_info_msg_0_}%{$reset_color%}"
    PROMPT="%{$fg[red]%}%n%{$fg[white]%}:%{$fg[yellow]%}%~ %(!.#.$)%{$reset_color%} "
}


# Load up editor when hitting ^x^x
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^x^x' edit-command-line

# Vim keybindings
bindkey -v

# modify the path
export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:/sbin"
export PATH="$PATH::/opt"

# go path
export GOPATH="$HOME/Sources/go"
export PATH="$PATH:$GOPATH/bin"
if [ ! -d $GOPATH ]; then
    mkdir -p $GOPATH
fi

# npm path
export PATH="$PATH:$HOME/.local/npm-global/bin"

# power
alias bork='systemctl poweroff'

##File associations
function openVideo() {
    ext=$(echo $1 | cut -f 1 -d '.')
	vlc "$@" 2>/dev/null &
}
alias -s {ts,mkv,mp3,mp4,srt,avi}="openVideo"
alias -s {jpg,jpeg,png,tiff,pdf,html}="chromium"
alias -s {zip}="unzip"
alias -s {jar}='java -jar'

# Docker ctf container
alias dctf-start='docker run --rm -d -v $PWD:/pwd --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --name ctf -i ctf'
alias dctf='docker exec -it ctf /bin/zsh'
alias djupyter='docker run --rm -v $PWD:/home/jovyan/work --name jupyter -i -p 8888:8888 jupyter/scipy-notebook'
alias djupytertf='docker run --rm -v $PWD:/home/jovyan/work --name jupyter -i -p 8888:8888 -p 6006:6006 --gpus all jupyter/tensorflow-notebook'

# misc
alias lsa='ls -A'
test "${PS1+set}" && CDPATH=".:$HOME/Sources/go/src/github.com/danielthatcher:$HOME/Projects"
alias e='vim'
alias ef='vim -c :Files'
alias t='tmux'
alias snapshot='sudo btrfs subvolume snapshot / /btrfs/backups/$(date +%F-%H)'
alias clip='xclip -selection clipboard'

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Local
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

# Plugins
ZSH_PLUGIN_DIR="$HOME/.config/zsh/plugins"

ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=2"
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=30
ZSH_AUTOSUGGEST_USE_ASYNC=1
ZSH_AUTOSUGGEST_MANUAL_REBIND=1
ZSH_AUTOSUGGEST_HISTORY_IGNORE="cd *"
[ -f $ZSH_PLUGIN_DIR/zsh-autosuggestions/zsh-autosuggestions.zsh ] && source $ZSH_PLUGIN_DIR/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey '^ ' autosuggest-accept
