# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _correct
zstyle ':completion:*' insert-unambiguous false
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=** r:|=**'
zstyle ':completion:*' max-errors 2
zstyle ':completion:*' menu select=long
zstyle ':completion:*' original true
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle :compinstall filename '/home/daniel/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt extendedglob
unsetopt beep notify
# End of lines configured by zsh-newuser-install

autoload -U colors
colors
PROMPT="%{$fg[cyan]%}%n%{$fg[white]%}:%{$fg[yellow]%}%~ %(!.#.$)%{$reset_color%} "

# modify the path
export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:/sbin"
export PATH="$PATH::/opt"

# go path
export GOPATH="$HOME/Sources/go"
export PATH="$PATH:$GOPATH/bin"
if [ ! -d $GOPATH ]; then
    mkdir -p $GOPATH
fi

# power
alias bork='systemctl poweroff'

##File associations
function openVideo() {
    ext=$(echo $1 | cut -f 1 -d '.')
	vlc "$@" 2>/dev/null &
}
alias -s {ts,mkv,mp3,mp4,srt,avi}="openVideo"
alias -s {jpg,jpeg,png,tiff,pdf}="chromium"
alias -s {zip}="unzip"
alias -s {jar}='java -jar'

# misc
alias lsa='ls -A'

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Local
[ -f ~/.zshrc.local ] && source ~/.zshrc.local
